<?php
//require_once 'constants.php';
require 'constantst.php';
//include_once 'constants.php';
//include 'constantst.php';
echo "<br>";
//echo "DB Host : " .DB_HOST;
$array1 = [11,"text2"];
$array2 = [2, 1,'text'];
//$result = array_merge($array1, $array2);
//print_r($result);
echo "<hr>";
$result = $array1 + $array2;
print_r($result);
echo "<hr>";
$arr = [1, 5, 55, 1];
print_r(array_unique($arr));
echo "<hr>";
print_r($array2);
echo "<hr>";
print_r($arr);
echo "<hr>";
print_r(array_diff($array2, $arr));
echo "<hr>";
print_r(array_diff($arr, $array2));
echo "<hr>";
echo [1, 5, 55, true] == $arr;
//
/***string **/
echo "<h1>String</h1>";
echo strlen("hello");
echo "<hr>";
echo str_word_count("hello wold");
echo "<hr>";
echo strrev("hello wold");
echo "<hr>";
echo strpos("hello   wold", "lo");
echo "<hr>";
echo str_replace("  wold", "php", "hello   wold");
echo "<hr>";
echo strtoupper("hello Word");
echo "<hr>";
echo strtolower("Hello Word");
echo "<hr>";
echo str_ends_with("Hello Word", "Word");
echo "<hr>";
$str = "Hello word";
$res = explode( " ", $str);

print_r($res);
echo "<hr>";
$str2 = "Hello word Hello Php";
$res = explode( "Hello", "Hello word Hello Php");
print_r($res);
echo "<hr>";
$arr = array('Hello','World!','Beautiful','Day!');
echo implode(", ",$arr);

$x = 3;
$y = 2;
echo "<hr>";
$z = $x**$y;
echo $z;
echo "<hr>";
echo $z**0.5;
echo "<hr>";
echo sqrt(64);
$a = "10";
$b = 20;
echo "<hr>";
echo gettype($a);
echo "<hr>";
echo is_string($a);
echo "<hr>";
echo is_numeric($a);
echo "<hr>";
echo (int)$a + $b;
echo"<hr>";
echo(abs(-6.7));
echo"<hr>";
echo round((float)6.7831, 1);
echo"<hr>";
echo rand(100, 9999);
echo"<hr>";
$a = 10;
$b = 20;
echo"A : $a <br> B : $b";
echo"<hr>";
//$z = $a;
//$a = $b;
//$b = $z;
//echo"A : $a <br> B : $b";
echo"<hr>";
$a = $a + $b;
$b = $a - $b;
$a = $a - $b;
echo"A : $a <br> B : $b";
$array = [1, 3, 'string', true];
echo"<hr>";
print_r($array);
unset($array[2]);
echo"<hr>";
print_r($array);
echo"<hr>";
unset($a);
echo  isset($a)? "Ka":"Chka";
